spring:
  application:
    name: wwc
  datasource:
    url: jdbc:h2:file:./data/wwc_db;AUTO_SERVER=TRUE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      # Enable the web UI at /h2-console
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
